
### LISTAR SALAS
GET http://localhost:3000/salas

### Criar uma sala
POST http://localhost:3000/salas
Content-Type: application/json

{
    "nome": "sala dos jagas",
    "capacidade": 20
}

### TESTE PARA DAR ERRO NA HORA DE CADASTRO
POST http://localhost:3000/salas
Content-Type: application/json

{
    "nome": "",
    "capacidade": -10
}

### TESTE PARA DAR ERRO NA HORA DE CADASTRO
POST http://localhost:3000/salas
Content-Type: application/json

{
    "nome": "Teste",
    "capacidade": -10
}

### Buscar por ID
GET http://localhost:3000/salas/1

### Buscar por ID inexistente
GET http://localhost:3000/salas/100

### Atualizar
PUT http://localhost:3000/salas/1
Content-Type: application/json

{
    "nome": "Testando alterar",
    "capacidade": 100
}

### Deletar 
DELETE http://localhost:3000/salas/1